# Generated by Django 4.1.3 on 2022-11-27 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='age',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
