# Generated by Django 4.1.3 on 2022-11-28 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_feeding'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheetah',
            name='image',
            field=models.TextField(default='null', max_length=250),
            preserve_default=False,
        ),
    ]
